#!/usr/bin/env python3
"""Matched TWPICE statistics: per-level standard deviations, cloud fraction,
and the single-level fields the PDFs are drawn from.

Reads the SAM-TWPICE snapshot and the two STEAM runs generated by
generate.py, brings them onto a common resolution, and writes everything the
plotting script needs into twpice_stats.npz.

MATCHING. Horizontally the host is block-averaged 2x2, 100 m -> 200 m, which
is STEAM's own spacing and puts both on 1024 x 1024 over the same 204.8 km.

Vertically neither grid is free to move: STEAM's dz follows from dx through
the aspect-ratio scaling (38.8 m here) and the host's is stretched, 50 m near
the surface through 100 m across the free troposphere. So the standing rule is
applied per level: at each host level, whichever field is finer is block-
averaged by the nearest integer factor that brings the two spacings closest
together. For TWPICE the host is coarser everywhere, so in practice STEAM is
averaged over 1 level low down and 3 through the free troposphere, and the
residual mismatch stays within about 1.3x. The factor used at every level is
saved so the figure can state it.

Cloud fraction is the fraction of cells holding at least 0.01 g/kg of
condensate, thresholded AFTER coarsening -- the coarsened cell value is what
the resolved field says is there.

SAM fields. h is c_p times the archived MSE, which SAM stores in K and
non-frozen; nothing is reconstructed. qt is qv + qc + qi, excluding the
precipitating species (QR/QS/QG are archived but deliberately left out, the
same convention make_input_profiles.py uses for the driving profiles). There
is no QT or TABS field in the SAM output at all.

Comparison levels are the host's own, clipped to STEAM's 20 km top.

Usage: python compute_twpice_stats.py
"""

import sys
from pathlib import Path

import numpy as np
import netCDF4

from steam.constants import specific_heat_dry_air as cp

from common import (VARS, CLOUD_KGKG, PDF_LEVELS, coarsen_xy, match_factors,
                    reduce_source)

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
RUNS = REPO / "runs" / "hydro"
HOST = REPO / "data" / "twpice"
OUT = HERE / "twpice_stats.npz"

sys.path.insert(0, str(REPO))
from make_input_profiles import _twpice_field, read_var    # noqa: E402

SETS = ("c005", "c017")
XY_COARSEN = 2                 # host 100 m -> 200 m
SNAPSHOT = "0000003450"


def host_fields():
    """TWPICE h, qt, qc, qi on the 200 m grid, each (nx, ny, nz).

    Each 2048^2 x 255 field is 4.3 GB, so they are read and coarsened one at a
    time. The MSE file's horizontal axes are (x, y); the mixing-ratio files'
    are (y, x) -- hence the differing flag, as in make_input_profiles.py.

    Everything is cast to float64 at the moment of reading, before any
    arithmetic touches it. MSE is K-scale, where a float32 accumulator drifts
    (the standing gotcha), and doing it on read rather than at each reduction
    means a reduction added later cannot reintroduce the problem.
    """
    z = np.asarray(read_var(HOST / f"TWPICE_LPT_3D_QV_{SNAPSHOT}.nc", "z"),
                   dtype=np.float64)

    def load(name, y_first, scale):
        a = _twpice_field(HOST / f"TWPICE_LPT_3D_{name}_{SNAPSHOT}.nc",
                          name, y_first).astype(np.float64)
        c = coarsen_xy(a, XY_COARSEN)
        del a
        print(f"  {name} -> {c.shape}", flush=True)
        return c * scale

    h = load("MSE", False, cp)          # SAM stores MSE in K; h = cp * MSE
    qv = load("QV", True, 1e-3)         # SAM mixing ratios are g/kg
    qc = load("QC", True, 1e-3)
    qi = load("QI", True, 1e-3)
    qt = qv + qc + qi                   # no precipitating water, by ruling
    del qv

    fields = {"h": h, "qt": qt, "qc": qc, "qi": qi}
    # z last, to match STEAM's layout for the level reductions below.
    return z, {k: np.moveaxis(v, 0, -1) for k, v in fields.items()}


def steam_fields(set_tag):
    """STEAM h, qt, qc, qi, each (nx, ny, nz), and its z axis.

    h is cast to float64 on read for the same reason as MSE above; the mixing
    ratios are O(1e-2) and stay float32, which halves what has to be held.
    """
    ds = netCDF4.Dataset(RUNS / f"twpice_{set_tag}.nc")
    ds.set_auto_mask(False)
    z = ds.variables["z"][:].astype(np.float64)
    fields = {v: ds.variables[v][:] for v in VARS}
    fields["h"] = fields["h"].astype(np.float64)
    ds.close()
    print(f"steam {set_tag} loaded: {fields['h'].shape}", flush=True)
    return z, fields


def main():
    # The z axis alone is enough to fix the comparison levels and the
    # coarsening factors, so read one STEAM file's grid before loading
    # anything large. Sources are then loaded, reduced and freed one at a
    # time -- holding the host and both STEAM sets at once would be ~40 GB.
    with netCDF4.Dataset(RUNS / f"twpice_{SETS[0]}.nc") as ds:
        z_steam0 = ds.variables["z"][:].astype(np.float64)
    z_host = np.asarray(read_var(HOST / f"TWPICE_LPT_3D_QV_{SNAPSHOT}.nc",
                                 "z"), dtype=np.float64)
    z_levels = z_host[z_host <= z_steam0[-1]]
    n_steam, n_host = match_factors(z_levels, z_steam0)
    print(f"{z_levels.size} comparison levels to {z_levels[-1]:.0f} m; "
          f"STEAM coarsened by {sorted(set(n_steam.tolist()))}, "
          f"host by {sorted(set(n_host.tolist()))}", flush=True)

    out = {"z": z_levels, "n_steam": n_steam, "n_host": n_host,
           "cloud_kgkg": CLOUD_KGKG, "pdf_levels": np.array(PDF_LEVELS),
           "sets": np.array(SETS)}

    print("loading host", flush=True)
    z_host, host = host_fields()
    std, cf, slices = reduce_source(z_host, host, z_levels, n_host)
    del host
    for v in VARS:
        out[f"std_{v}_host"] = std[v]
    out["cf_host"] = cf
    for k, a in slices.items():
        out[f"pdf_{k}_host"] = a
    print("host reduced", flush=True)

    for tag in SETS:
        z_s, fields = steam_fields(tag)
        std, cf, slices = reduce_source(z_s, fields, z_levels, n_steam)
        del fields
        for v in VARS:
            out[f"std_{v}_{tag}"] = std[v]
        out[f"cf_{tag}"] = cf
        for k, a in slices.items():
            out[f"pdf_{k}_{tag}"] = a
        print(f"steam {tag} reduced", flush=True)

    np.savez_compressed(OUT, **out)
    print(f"wrote {OUT.name} ({OUT.stat().st_size / 1e6:.0f} MB)")


if __name__ == "__main__":
    main()
