[project]
name = "turbulon-analysis"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "matplotlib",
    "netCDF4",
    "objscale",
    "steam",
]

[tool.uv.sources]
steam = { path = "../turbulon-model", editable = true }
objscale = { path = "../objscale", editable = true }
