#!/usr/bin/env python3
"""Assemble the cloud-geometry comparison table in LaTeX.

One section per albedo threshold. Within each, the MODIS retrieval sits at
the top, ruled off from the four simulated cases below it (the two SAM LES
and STEAM at both flux amplitudes).

An italic entry is one where objscale warned about the fit -- too few
populated size bins, or too narrow a range of scales. Every SAM size
distribution earns one, because a single snapshot per case simply does not
carry the range; the dimensions, which are measured per object, do not.
Reading those numbers as measured would be a mistake, and italics say so on
the page rather than in a log.

MODIS values are read off Table 1 of DeWitt et al. (2026), "Toward less
subjective metrics for quantifying the shape and organization of clouds",
ACP 26, 6951-6971: the measured individual dimension D_i, the correlation
form of D_e, and beta, which is this repo's nested-perimeter exponent.
Uncertainties are dropped by request. That paper reports neither a cloud
fraction nor an area-distribution exponent, so those two cells are empty
rather than guessed.

Usage: python make_fractal_table.py
"""

from pathlib import Path

import numpy as np

from albedo import ALBEDO_THRESHOLDS, threshold_tag

HERE = Path(__file__).resolve().parent
OUT = HERE / "fractal_table.tex"

# metric key -> column header
COLUMNS = (
    ("cover", r"CF"),
    ("D_e", r"$D_e$"),
    ("D_f", r"$D_f$"),
    ("tau_area", r"$\tau_{\mathrm{area}}$"),
    ("tau_per", r"$\tau_{\mathrm{per}}$"),
)

# DeWitt et al. (2026) Table 1, by reflectance threshold. None = not reported.
MODIS = {
    0.1: {"cover": None, "D_e": 1.77, "D_f": 1.38,
          "tau_area": None, "tau_per": 1.26},
    0.2: {"cover": None, "D_e": 1.72, "D_f": 1.38,
          "tau_area": None, "tau_per": 1.29},
    0.3: {"cover": None, "D_e": 1.71, "D_f": 1.39,
          "tau_area": None, "tau_per": 1.34},
}

# label -> (npz file, key prefix within it)
CASES = (
    ("SAM-GATE", "sam_fractal_metrics.npz", "gate"),
    ("SAM-TWPICE", "sam_fractal_metrics.npz", "twpice"),
    (r"STEAM $c = 0.05$", "fractal_metrics_C1small.npz", None),
    (r"STEAM $c = 0.17$", "fractal_metrics_C1large.npz", None),
)


def cell(value, warned):
    """One table entry: two decimals, italic if objscale warned, -- if absent."""
    if value is None or not np.isfinite(value):
        return "--"
    text = f"{value:.2f}"
    return rf"\textit{{{text}}}" if warned else text


def case_row(label, data, prefix, R):
    tag = threshold_tag(R) if prefix is None else f"{prefix}_{threshold_tag(R)}"
    cells = []
    for key, _ in COLUMNS:
        full = f"{tag}_{key}"
        if full not in data:
            cells.append("--")
            continue
        warned = bool(data.get(f"{tag}_warn_{key}", False))
        cells.append(cell(float(data[full]), warned))
    return f"{label} & " + " & ".join(cells) + r" \\"


def main():
    loaded = {}
    for _, filename, _ in CASES:
        if filename not in loaded:
            path = HERE / filename
            if not path.exists():
                raise SystemExit(
                    f"{filename} not found -- run compute_fractal_metrics.py "
                    f"(once per set) and compute_sam_fractal.py first")
            loaded[filename] = dict(np.load(path, allow_pickle=False))

    lines = [
        r"% Generated by make_fractal_table.py -- do not edit by hand.",
        r"\begin{table*}[t]",
        r"\caption{Cloud geometry against reflectance threshold $R$. "
        r"$D_e$ is the ensemble (correlation) fractal dimension, $D_f$ the "
        r"individual fractal dimension ($D_i$ in DeWitt et al., 2026), and "
        r"$\tau_{\mathrm{area}}$, $\tau_{\mathrm{per}}$ the area and "
        r"nested-perimeter size-distribution exponents ($\beta$ in that "
        r"paper). CF is cloud fraction. MODIS values are from that paper's "
        r"Table 1, which reports neither CF nor $\tau_{\mathrm{area}}$. "
        r"Italic entries are fits objscale flagged as resting on too few "
        r"size bins or too narrow a range of scales.}",
        r"\label{tab:cloud geometry}",
        r"\begin{tabular}{l" + "c" * len(COLUMNS) + "}",
        r"\tophline",
        " & " + " & ".join(head for _, head in COLUMNS) + r" \\",
        r"\middlehline",
    ]

    for i, R in enumerate(ALBEDO_THRESHOLDS):
        if i:
            lines.append(r"\middlehline")
        lines.append(rf"\multicolumn{{{len(COLUMNS) + 1}}}{{l}}"
                     rf"{{\textbf{{$R > {R:g}$}}}} \\")
        modis = MODIS[R]
        lines.append("MODIS & "
                     + " & ".join(cell(modis[key], False) for key, _ in COLUMNS)
                     + r" \\")
        lines.append(rf"\cline{{1-{len(COLUMNS) + 1}}}")
        for label, filename, prefix in CASES:
            lines.append(case_row(label, loaded[filename], prefix, R))

    lines += [r"\bottomhline", r"\end{tabular}",
              r"\belowtable{}", r"\end{table*}"]

    text = "\n".join(lines) + "\n"
    OUT.write_text(text)
    print(text)
    print(f"wrote {OUT.name}")


if __name__ == "__main__":
    main()
